service: task_manager
image: gtex/task_manager
servers:
  web:
    - gtex@localhost
registry:
  username: gtex
  password:
    - LOBDEV2025
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
